configuration: Release

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore
  
# package Web Application project for Web Deploy
build:
  verbosity: minimal
  publish_wap: true

# deploy site on Azure
environment:
  site_to_deploy: MyMVC

deploy:
  - provider: Environment
    name: MyMVC
    site_name: $(site_to_deploy)
